language: python

python:
  - 3.5

# services: postgresql

env:
  - DJANGO=1.11.5

before_install:
  - export DJANGO_SETTINGS_MODULE=sign_files.settings
  - export PYTHONPATH=$HOME/builds/jchierro/sign-files-with-pyOpenSSL
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
#  - pip install psycopg2 --quiet

# before_script:
#  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - cd sign_files
  - python3 manage.py test
#  - python manage.py syncdb --noinput
