language: python

python:
  - 3.5

env:
  - DJANGO=1.11.5

before_install:
  - export DJANGO_SETTINGS_MODULE=sign_files.settings
  - export PYTHONPATH=$HOME/builds/jchierro/sign-files-with-pyOpenSSL
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

script:
  - cd sign_files
  - python3 manage.py test
